// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AirStat struct {
	ID           int64
	Co2Ppm       int32
	TempTick     int32
	HumidityTick int32
	CreatedAt    pgtype.Timestamp
}
